services:
  db:
    image: postgres:16
    container_name: postgres-eccomerce-auth-service
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER}']
      interval: 5s
      timeout: 5s
      retries: 5
    
  backend:
    build: .
    container_name: ecommerce-auth-service
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - '3000:3000'
    command: sh -c "npm run migration:run && npm run start:dev"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  pgdata: